### ISSUE TITLE
Modify level.dat fields

### ISSUE THREAD

**Issue by gbaman** [Amulet-Team/Amulet-NBT#36]
I'm currently trying to find a way to programmatically edit individual fields in a Bedrock (1.17) level.dat file.

Using the getting started example, I've got as far as being able to load in the level.dat file, but not much further in actually reading and writing the individual fields.
A quick example running through reading/writing would be super helpful.
I'm also not sure if I should be using Amulet-NBT or Amulet-Core? I've taken a look at using Amulet-Core as well with the below code with no luck.
```python
import amulet.libs.leveldb
level = amulet.libs.leveldb.LevelDB("world_folder_name")
for item in level.iterate(): # A blank iterator
   print(item) 
print(a.get("allowmobs".encode())) # Errors with KeyError: "Key b'allowmobs' not found in database."
```

Any advice or suggestions would be greatly appreciated!

**Comment by gentlegiantJGC** [comment]
The code you have there is iterating the leveldb database (storage for chunk and other data).

If you just want to edit the level.dat file you can use this class.
https://github.com/Amulet-Team/Amulet-Core/blob/master/amulet/level/formats/leveldb_world/format.py#L44

Using that with the level open in game or with Amulet may cause issues so make sure it is not open elsewhere first.

Questions are better asked in our discord server. We have a chat for python users.
