### ISSUE TITLE
Fails to pickup system-wide numpy installation

### ISSUE THREAD

**Issue by PureTryOut** [Amulet-Team/Amulet-NBT#4]
I have numpy 1.18.4 installed system-wide, but when running `python3 setup.py build` to make a distribution package for Amulet-NBT, it still tries to download numpy from pip. Because this build system blocks network access for builds, this obviously fails.

Cython however _is_ picked up from the system.

**Comment by gentlegiantJGC** [comment]
This seems like an issue with your environment not this library.

**Comment by PureTryOut** [comment]
I'm sorry, but that's just not true, you made a wrong assumption. I have numpy installed from my systems package manager and the same library is used by tons of other packages in this distribution. Amulet-NBT is the only one having trouble with it.

**Comment by PureTryOut** [comment]
Like I said, I have 1.18.4 installed. I'm not running in a virtual environment, I'm installing it system-wide, "global", with the eventual goal to package it for my distro as a native system package.
