### ISSUE TITLE
Loading Minecraft region (*.mca) files

### ISSUE THREAD

**Issue by ouroborus** [Amulet-Team/Amulet-NBT#42]
Minecraft region files aren't entirely NBT so you can't load them directly with Amulet-NBT. This helper function should be able to extract and load the chunks.

```python
from struct import iter_unpack, unpack
import amulet_nbt as nbt
import zlib
import io

def load_mca(filename):
    chunks = []
    with open(filename, 'rb') as f:
        for (pointer,) in iter_unpack('>I', f.read(4096)):
            if pointer == 0:
                continue
            offset = ((pointer >> 8) & 0xffffff) * 4096
            f.seek(offset, io.SEEK_SET)
            size = unpack('>I', f.read(4))[0]
            offset += 5
            f.seek(offset, io.SEEK_SET)
            tags = f.read(size)
            tags = zlib.decompress(tags)
            tags = nbt.load(tags, compressed=False)
            chunks.append(tags)
    return chunks
```

**Comment by gentlegiantJGC** [comment]
This is beyond the scope of this library.
This is implemented in the Amulet Core library.

**Comment by ouroborus** [comment]
@gentlegiantJGC That's good to know. Amulet-Core didn't and still doesn't show up for me in Google or PyPI searches for map or nbt editors. The Amulet map editor didn't show up for me in Google searches (though it does now, about half-way down the results).
