### ISSUE TITLE
Undefined symbol: PyMemoryview_Check

### ISSUE THREAD

**Issue by ItsYogSothoth** [Amulet-Team/Amulet-NBT#44]
When trying to run Amulet Map Editor this error is thrown from Amulet-NBT module:
```
ImportError: /home/yogsot/.pyenv/versions/3.7.16/lib/python3.7/site-packages/amulet_nbt/_load_nbt.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyMemoryview_Check
```

After searching I found Python documentation where "view" is capitalized.Is this a case of typo in code?
https://docs.python.org/3.7/c-api/memoryview.html

**Comment by MajliTech** [comment]
The same error i got.

**Comment by KodexKy** [comment]
This comes from a bug in cython 3.0.0b1. https://github.com/cython/cython/issues/5270

**Comment by KodexKy** [comment]
Quick and dirty workaround for those urgently needing this to work. Revert commit c0aa27994fed860eb31f706bd5bdab4642b7aab8 and rebuild.

**Comment by MajliTech** [comment]
I reverted, and now what? `python3.7 -m pip install .`?

**Comment by KodexKy** [comment]
I used `pip install -e .`

**Comment by gentlegiantJGC** [comment]
The two solutions for this are
1) We wait for Cython to fix the bug
2) We modify the requirements to disallow the latest beta

**Comment by MajliTech** [comment]
> I used `pip install -e .`

What's the difference?
