### ISSUE TITLE
Error decoding NBT data from my bedrock world.

### ISSUE THREAD

**Issue by zimage** [Amulet-Team/Amulet-NBT#53]
I am getting a UnicodeDecodeError exception when parsing nbt from my vanilla bedrock world. Am I doing something wrong, is there a problem with my world data, or is there a bug in the library?

```python
from leveldb import LevelDB
from struct import pack
import amulet_nbt

x = 1
z = 0
tag = b'\x31'
key = pack('iic', x, z, tag)
print("Key-\n", key)

db = LevelDB("/home/ubuntu/tmp/SpringbeanFarm/db", False)
value = db.get(key)
print("Value-\n", value)
nbt = amulet_nbt.load_array(value, count = -1, little_endian=True)
```

The NBT is 99754 bytes, so I can't post the output here. I have it at this [pastebin](https://pastebin.com/x74UfcXr).

**Comment by gentlegiantJGC** [comment]
The default `string_decoder` is for Java's modified utf-8.
This should fix the issue.
```py
from amulet_nbt import load_array, utf8_decoder
nbt = load_array(value, count = -1, compressed=False, little_endian=True, string_decoder=utf8_decoder)
```

**Comment by zimage** [comment]
That did it. Thanks for the help.
