### ISSUE TITLE
Support unnamed binary NBT

### ISSUE THREAD

**Issue by shBLOCK** [Amulet-Team/Amulet-NBT#88]
I'm working on a mod that does python inter-op through WebSocket, I want to use this great library to handle NBT, but currently the library doesn't seem to support reading/writing unnamed raw binary NBT.

Reading raw unnamed NBT (eg. `b"\01\05"`, a raw `ByteTag(5)`) results in errors.
All write methods have a `name` argument, which defaults to `""`, so it always puts a `\00\00` for an empty name in the result, passing `None` isn't supported.

Currently, the workaround is to manually adding/removing the two null bytes.
I'd suggest making the write methods accept `None` as a valid value for the `name` argument, which would make it skip writing the name string; for the reading methods, add a `named` argument that defaults to `True` to allow reading unnamed NBTs while keeping backward compatibility.

**Comment by gentlegiantJGC** [comment]
Please can you provide an example where this is used. I have not seen this before.

**Comment by shBLOCK** [comment]
I'm writing a mod that does Python - Minecraft interop via WebSocket.
So I need to decode/encode bnbt in Python.
In a mc mod, using `NbtIo.writeAnyTag(Tag, DataOutput)` would result in this kind of unnamed binary NBT data.

It would also be useful for advanced users who want to do some "post-processing" on the serialized binary NBT from the library. 

In such cases manually removing/adding the two null bytes just seems too hacky, and incurs immense performance loss if reading from memoryviews, since you can't easily concatinate two memoryviews in python.

**Comment by shBLOCK** [comment]
Another example would be if someone wants to read a compound tag within a big NBT file (at a certain byte offset) (that they don't want to parse completely as it's too big).

**Comment by shBLOCK** [comment]
I looked a bit at the code and I don't think this would be too hard to implement? I suppose changing the signitures of all the writexxx functions would be a bit of a pain though.
I'm not familiar with C++ pybind so unfortunately I won't be able to do that myself.

**Comment by gentlegiantJGC** [comment]
I have never interacted with that format. We only interact with data saved to disk.
I don't have any reason to implement it myself but open to a pull request implementing it.

**Comment by shBLOCK** [comment]
Just to be clear, the only real code change (excluding related changes to function signatures, etc.) is to make the `write_string` line here optional (don't write name if `name` is `NULL`).
https://github.com/Amulet-Team/Amulet-NBT/blob/7f40e6923f57a0feaece68383b75393b6fcf7899/src/amulet_nbt/cpp/nbt_encoding/binary/write_binary.cpp#L171-L173
I do understand that this isn't all that useful for reading NBT files, maybe someday I will try to do a PR on this.

**Comment by shBLOCK** [comment]
Oh, I closed this by accident, should I leave this open?
